# Generated by Django 3.1 on 2020-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0002_auto_20200812_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarysignal',
            name='TimeFrame',
            field=models.CharField(default='1D', max_length=30),
        ),
    ]
