# Generated by Django 3.1 on 2020-08-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0003_binarysignal_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarysignal',
            name='TakeProfit2',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='binarysignal',
            name='TakeProfit3',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='binarysignal',
            name='TakeProfit4',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
