# Generated by Django 3.1 on 2020-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0006_auto_20200813_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarysignal',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
