# Generated by Django 3.1 on 2020-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0013_auto_20200818_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarysignal',
            name='LivePrice',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='binarysignal',
            name='Publisher',
            field=models.CharField(choices=[('@Secret_army', '@Secret_army'), ('@mhfateminia', '@mhfateminia'), ('@peyman_gh', '@peyman_gh'), ('@Eslaaamiii', '@Eslaaamiii'), ('@Reza_Esfilar', '@Reza_Esfilar')], max_length=30),
        ),
    ]
