# Generated by Django 3.1 on 2020-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0015_auto_20200820_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favlist',
            name='SymbolTitle',
        ),
        migrations.AlterField(
            model_name='favlist',
            name='IsStopLossed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='IsTP1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='IsTP2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='IsTP3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='IsTP4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='IsTriggered',
            field=models.BooleanField(default=False),
        ),
    ]
