# Generated by Django 3.1 on 2020-08-20 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptosignal', '0019_remove_favlist_liveprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='favlist',
            name='Userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
