# Generated by Django 3.1 on 2020-08-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0020_favlist_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favlist',
            old_name='binarysignal',
            new_name='SymbolTitle',
        ),
    ]
