# Generated by Django 3.1 on 2020-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0021_auto_20200820_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favlist',
            name='Userid',
        ),
        migrations.AddField(
            model_name='favlist',
            name='User',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
