# Generated by Django 3.1.2 on 2020-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignal', '0025_auto_20200822_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarysignal',
            name='TelegramMessageId',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
